services:
  web:
    build: .
    container_name: naiprints3d-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8001:8001"
    environment:
      PORT: "8001"
      SQLITE_PATH: /app/media/db.sqlite3
      REQUIRE_SQLITE_FILE: "True"
    volumes:
      - media_data:/app/media
      - static_data:/app/staticfiles

volumes:
  media_data:
  static_data:
