services:
  web:
    build: .
    container_name: naiprints3d-web
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      SQLITE_PATH: /app/data/db.sqlite3
    volumes:
      - sqlite_data:/app/data
      - media_data:/app/media
      - static_data:/app/staticfiles

volumes:
  sqlite_data:
  media_data:
  static_data:
